[package]
name = "game-of-life"
version = "0.0.0"
authors = [
    "Arcterus <arcterus@mail.com>",
    "indiv0 <contact@nikitapek.in>"
]

[[bin]]
name = "life"
path = "src/life.rs"

[dependencies]
piston = "0.15.1"
piston2d-graphics = "0.11.0"
pistoncore-glutin_window = "0.17.1"
piston2d-opengl_graphics = "0.19.0"
